# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69e0da7a40b97e1cea3c2304356ced9ad88e327ccbff2b9126952318351b52226babccec353c38f414738c5df70fbd1cc0aa321bf0226ab61970007aad0ec38d

test:
  secret_key_base: 8e110ecbe2bc16af8a3387362be80cff868b71de095c05759eac200d5356203e43e7228d6d55464041b5415f7cceab1724bb48606c1bfc9413d9c90818bff890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
